#!/usr/bin/env node
/**
 * Turns a MongoDB export (the EJSON files produced by export.sh) into a SQL
 * file that loads the data into Supabase.
 *
 * It emits SQL rather than writing to the database directly, for two reasons:
 * the result is reviewable before it touches anything, and password hashes
 * can be carried across, which the Supabase Auth admin API cannot do (it
 * only accepts plaintext passwords).
 *
 * Usage:
 *   node scripts/import-mongo.mjs [exportDir] [outFile]
 *   node scripts/import-mongo.mjs avsph_export supabase/import/import.sql
 */

import { createHash } from "node:crypto";
import { readFileSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";

const exportDir = process.argv[2] ?? "avsph_export";
const outFile = process.argv[3] ?? "supabase/import/import.sql";

// Fixed namespace, so re-running produces identical ids and the import stays
// repeatable instead of duplicating everything on a second run.
const NAMESPACE = "6f8d3a1e-2c47-4b19-9e5a-0d7c8b4f1a23";

/** RFC 4122 v5 UUID, used to derive a stable uuid from a Mongo ObjectId. */
const uuidV5 = (name) => {
  const ns = Buffer.from(NAMESPACE.replace(/-/g, ""), "hex");
  const hash = createHash("sha1")
    .update(Buffer.concat([ns, Buffer.from(name, "utf8")]))
    .digest();
  const bytes = Buffer.from(hash.subarray(0, 16));
  bytes[6] = (bytes[6] & 0x0f) | 0x50;
  bytes[8] = (bytes[8] & 0x3f) | 0x80;
  const hex = bytes.toString("hex");
  return [
    hex.slice(0, 8),
    hex.slice(8, 12),
    hex.slice(12, 16),
    hex.slice(16, 20),
    hex.slice(20, 32),
  ].join("-");
};

// ── EJSON normalisation ───────────────────────────────────────────────────

const oid = (value) => {
  if (value == null) return null;
  if (typeof value === "string") return value;
  if (typeof value === "object" && typeof value.$oid === "string") return value.$oid;
  return null;
};

const plain = (value) => {
  if (value === null || value === undefined) return null;
  if (Array.isArray(value)) return value.map(plain);
  if (typeof value !== "object") return value;

  if ("$oid" in value) return value.$oid;
  if ("$date" in value) {
    const d = value.$date;
    const ms = typeof d === "object" && d?.$numberLong ? Number(d.$numberLong) : d;
    return new Date(ms).toISOString();
  }
  if ("$numberDecimal" in value) return Number(value.$numberDecimal);
  if ("$numberLong" in value) return Number(value.$numberLong);
  if ("$numberInt" in value) return Number(value.$numberInt);
  if ("$numberDouble" in value) return Number(value.$numberDouble);

  const out = {};
  for (const [k, v] of Object.entries(value)) out[k] = plain(v);
  return out;
};

const readCollection = (name) => {
  const path = join(exportDir, `${name}.json`);
  if (!existsSync(path)) {
    console.warn(`  ! ${name}.json not found, skipping`);
    return [];
  }
  const raw = readFileSync(path, "utf8").trim();
  if (!raw) return [];
  try {
    return JSON.parse(raw).map(plain);
  } catch (error) {
    throw new Error(`${name}.json is not valid JSON: ${error.message}`);
  }
};

// ── SQL helpers ───────────────────────────────────────────────────────────

const sqlStr = (value) => {
  if (value === null || value === undefined || value === "") return "null";
  return `'${String(value).replace(/'/g, "''")}'`;
};
const sqlNum = (value) =>
  value === null || value === undefined || value === "" || Number.isNaN(Number(value))
    ? "null"
    : String(Number(value));
const sqlBool = (value, fallback = true) =>
  value === null || value === undefined ? String(fallback) : String(Boolean(value));
const sqlTs = (value) => (value ? sqlStr(value) : "now()");
const sqlDate = (value) => (value ? sqlStr(String(value).slice(0, 10)) : "null");
const sqlArr = (values) =>
  !Array.isArray(values) || values.length === 0
    ? "'{}'"
    : `array[${values.map((v) => sqlStr(v)).join(", ")}]::text[]`;

const oneOf = (value, allowed, fallback) =>
  allowed.includes(value) ? value : fallback;

// bcrypt hashes are what Supabase Auth stores, so an old backend using bcrypt
// means everyone keeps their current password. Anything else has to reset.
const isBcrypt = (hash) =>
  typeof hash === "string" && /^\$2[aby]?\$\d{2}\$.{53}$/.test(hash);

// ── Build ─────────────────────────────────────────────────────────────────

console.log(`Reading export from ${exportDir}/`);

const businesses = readCollection("businesses");
const admins = readCollection("admins");
const clients = readCollection("clients");
const profiles = readCollection("compensation_profiles");
const staff = readCollection("staff");

const lines = [];
const stats = { needsPasswordReset: [], skipped: [] };

lines.push("-- Generated by scripts/import-mongo.mjs. Do not edit by hand.");
lines.push(`-- Source: ${exportDir}/  Generated: ${new Date().toISOString()}`);
lines.push("--");
lines.push("-- Ids are derived from the Mongo ObjectId with a fixed UUIDv5");
lines.push("-- namespace, so re-running this file updates the same rows rather");
lines.push("-- than inserting duplicates.");
lines.push("");
lines.push("begin;");
lines.push("");

// Businesses
lines.push("-- ── businesses ──────────────────────────────────────────────");
for (const b of businesses) {
  const id = oid(b._id);
  if (!id) continue;
  lines.push(
    `insert into public.businesses (id, legacy_id, name, slug, description, logo, website, is_active, created_at, updated_at) values (` +
      `'${uuidV5(id)}', ${sqlStr(id)}, ${sqlStr(b.name)}, ${sqlStr(b.slug)}, ${sqlStr(b.description)}, ` +
      `${sqlStr(b.logo)}, ${sqlStr(b.website)}, ${sqlBool(b.isActive)}, ${sqlTs(b.createdAt)}, ${sqlTs(b.updatedAt)}) ` +
      `on conflict (id) do update set name = excluded.name, slug = excluded.slug, ` +
      `description = excluded.description, logo = excluded.logo, website = excluded.website, ` +
      `is_active = excluded.is_active;`,
  );
}
lines.push("");

// Admins: auth user, identity, profile row, business memberships
lines.push("-- ── admins ──────────────────────────────────────────────────");
for (const a of admins) {
  const id = oid(a._id);
  if (!id || !a.email) continue;
  const uuid = uuidV5(id);
  const hash = isBcrypt(a.password) ? a.password : null;
  if (!hash) stats.needsPasswordReset.push(a.email);

  lines.push(
    `insert into auth.users (instance_id, id, aud, role, email, encrypted_password, ` +
      `email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data) values (` +
      `'00000000-0000-0000-0000-000000000000', '${uuid}', 'authenticated', 'authenticated', ` +
      `${sqlStr(a.email)}, ${hash ? sqlStr(hash) : `crypt(gen_random_uuid()::text, gen_salt('bf'))`}, ` +
      `${sqlTs(a.createdAt)}, ${sqlTs(a.createdAt)}, ${sqlTs(a.updatedAt)}, ` +
      `'{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb) ` +
      `on conflict (id) do nothing;`,
  );
  lines.push(
    `insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at) ` +
      `values ('${uuid}', '${uuid}', jsonb_build_object('sub', '${uuid}', 'email', ${sqlStr(a.email)}, 'email_verified', true), ` +
      `'email', now(), now(), now()) on conflict (provider, provider_id) do nothing;`,
  );
  lines.push(
    `insert into public.admins (id, legacy_id, email, first_name, last_name, role, is_active, created_at, updated_at) values (` +
      `'${uuid}', ${sqlStr(id)}, ${sqlStr(a.email)}, ${sqlStr(a.firstName)}, ${sqlStr(a.lastName)}, ` +
      `${sqlStr(oneOf(a.role, ["super-admin", "admin"], "admin"))}::public.admin_role, ` +
      `${sqlBool(a.isActive)}, ${sqlTs(a.createdAt)}, ${sqlTs(a.updatedAt)}) ` +
      `on conflict (id) do update set email = excluded.email, first_name = excluded.first_name, ` +
      `last_name = excluded.last_name, role = excluded.role, is_active = excluded.is_active;`,
  );
  for (const businessId of a.businessIds ?? []) {
    const bid = oid(businessId);
    if (!bid) continue;
    lines.push(
      `insert into public.admin_businesses (admin_id, business_id) values ('${uuid}', '${uuidV5(bid)}') on conflict do nothing;`,
    );
  }
}
lines.push("");

// business.adminIds is the same relationship seen from the other side.
lines.push("-- ── business admin memberships (from business.adminIds) ─────");
for (const b of businesses) {
  const bid = oid(b._id);
  if (!bid) continue;
  for (const adminId of b.adminIds ?? []) {
    const aid = oid(adminId);
    if (!aid) continue;
    lines.push(
      `insert into public.admin_businesses (admin_id, business_id) values ('${uuidV5(aid)}', '${uuidV5(bid)}') on conflict do nothing;`,
    );
  }
}
lines.push("");

// Clients
lines.push("-- ── clients ─────────────────────────────────────────────────");
for (const c of clients) {
  const id = oid(c._id);
  const bid = oid(c.businessId);
  if (!id || !bid) {
    if (id) stats.skipped.push(`client ${id} (no businessId)`);
    continue;
  }
  lines.push(
    `insert into public.clients (id, legacy_id, business_id, name, company_name, contact_person, email, phone, ` +
      `website, address, billing_info, tags, logo_url, notes, status, is_active, created_at, updated_at) values (` +
      `'${uuidV5(id)}', ${sqlStr(id)}, '${uuidV5(bid)}', ${sqlStr(c.name)}, ${sqlStr(c.companyName)}, ` +
      `${sqlStr(c.contactPerson)}, ${sqlStr(c.email)}, ${sqlStr(c.phone)}, ${sqlStr(c.website)}, ` +
      `${sqlStr(c.address)}, ${sqlStr(c.billingInfo)}, ${sqlArr(c.tags)}, ${sqlStr(c.logoUrl)}, ${sqlStr(c.notes)}, ` +
      `${sqlStr(oneOf(c.status, ["active", "inactive"], "active"))}::public.client_status, ` +
      `${sqlBool(c.isActive)}, ${sqlTs(c.createdAt)}, ${sqlTs(c.updatedAt)}) ` +
      `on conflict (id) do update set name = excluded.name, company_name = excluded.company_name, ` +
      `contact_person = excluded.contact_person, email = excluded.email, phone = excluded.phone, ` +
      `website = excluded.website, address = excluded.address, billing_info = excluded.billing_info, ` +
      `tags = excluded.tags, logo_url = excluded.logo_url, notes = excluded.notes, ` +
      `status = excluded.status, is_active = excluded.is_active;`,
  );
}
lines.push("");

// Compensation profiles
lines.push("-- ── compensation profiles ───────────────────────────────────");
for (const p of profiles) {
  const id = oid(p._id);
  const bid = oid(p.businessId);
  if (!id || !bid) {
    if (id) stats.skipped.push(`compensation profile ${id} (no businessId)`);
    continue;
  }
  lines.push(
    `insert into public.compensation_profiles (id, legacy_id, business_id, name, currency, hourly_rate, ` +
      `overtime_rate_multiplier, sunday_rate_multiplier, night_differential_rate_multiplier, ` +
      `is_transportation_allowance_enabled, transportation_allowance_monthly_amount, is_sss_enabled, ` +
      `is_pag_ibig_enabled, is_phil_health_enabled, sss_deduction_fixed_amount, ` +
      `pag_ibig_deduction_fixed_amount, phil_health_deduction_fixed_amount, effective_from, effective_to, ` +
      `is_active, created_at, updated_at) values (` +
      `'${uuidV5(id)}', ${sqlStr(id)}, '${uuidV5(bid)}', ${sqlStr(p.name)}, ${sqlStr(p.currency ?? "PHP")}, ` +
      `${sqlNum(p.hourlyRate ?? 0)}, ${sqlNum(p.overtimeRateMultiplier ?? 1)}, ${sqlNum(p.sundayRateMultiplier ?? 1)}, ` +
      `${sqlNum(p.nightDifferentialRateMultiplier ?? 1)}, ${sqlBool(p.isTransportationAllowanceEnabled, false)}, ` +
      `${sqlNum(p.transportationAllowanceMonthlyAmount ?? 0)}, ${sqlBool(p.isSssEnabled, false)}, ` +
      `${sqlBool(p.isPagIbigEnabled, false)}, ${sqlBool(p.isPhilHealthEnabled, false)}, ` +
      `${sqlNum(p.sssDeductionFixedAmount ?? 0)}, ${sqlNum(p.pagIbigDeductionFixedAmount ?? 0)}, ` +
      `${sqlNum(p.philHealthDeductionFixedAmount ?? 0)}, ` +
      `coalesce(${sqlDate(p.effectiveFrom)}::date, current_date), ${sqlDate(p.effectiveTo)}::date, ` +
      `${sqlBool(p.isActive)}, ${sqlTs(p.createdAt)}, ${sqlTs(p.updatedAt)}) ` +
      `on conflict (id) do update set name = excluded.name, currency = excluded.currency, ` +
      `hourly_rate = excluded.hourly_rate, is_active = excluded.is_active;`,
  );
}
lines.push("");

// Staff: auth user, identity, profile row, embedded documents
lines.push("-- ── staff ───────────────────────────────────────────────────");
for (const s of staff) {
  const id = oid(s._id);
  const bid = oid(s.businessId);
  if (!id || !bid || !s.email) {
    if (id) stats.skipped.push(`staff ${id} (missing businessId or email)`);
    continue;
  }
  const uuid = uuidV5(id);
  const hash = isBcrypt(s.password) ? s.password : null;
  if (!hash) stats.needsPasswordReset.push(s.email);

  const clientId = oid(s.clientId);
  const profileId = oid(s.compensationProfileId);

  lines.push(
    `insert into auth.users (instance_id, id, aud, role, email, encrypted_password, ` +
      `email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data) values (` +
      `'00000000-0000-0000-0000-000000000000', '${uuid}', 'authenticated', 'authenticated', ` +
      `${sqlStr(s.email)}, ${hash ? sqlStr(hash) : `crypt(gen_random_uuid()::text, gen_salt('bf'))`}, ` +
      `${sqlTs(s.createdAt)}, ${sqlTs(s.createdAt)}, ${sqlTs(s.updatedAt)}, ` +
      `'{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb) ` +
      `on conflict (id) do nothing;`,
  );
  lines.push(
    `insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at) ` +
      `values ('${uuid}', '${uuid}', jsonb_build_object('sub', '${uuid}', 'email', ${sqlStr(s.email)}, 'email_verified', true), ` +
      `'email', now(), now(), now()) on conflict (provider, provider_id) do nothing;`,
  );
  lines.push(
    `insert into public.staff (id, legacy_id, business_id, client_id, compensation_profile_id, email, ` +
      `first_name, last_name, phone, position, department, date_hired, salary, salary_type, bill_rate_usd, ` +
      `employment_type, status, notes, photo_url, is_active, created_at, updated_at) values (` +
      `'${uuid}', ${sqlStr(id)}, '${uuidV5(bid)}', ${clientId ? `'${uuidV5(clientId)}'` : "null"}, ` +
      `${profileId ? `'${uuidV5(profileId)}'` : "null"}, ${sqlStr(s.email)}, ${sqlStr(s.firstName)}, ` +
      `${sqlStr(s.lastName)}, ${sqlStr(s.phone)}, ${sqlStr(s.position ?? "Staff")}, ${sqlStr(s.department)}, ` +
      `coalesce(${sqlDate(s.dateHired)}::date, current_date), ${sqlNum(s.salary)}, ` +
      `${s.salaryType ? `${sqlStr(oneOf(s.salaryType, ["hourly", "daily", "monthly", "annual"], "hourly"))}::public.salary_type` : "null"}, ` +
      `${sqlNum(s.billRateUsd)}, ` +
      `${sqlStr(oneOf(s.employmentType, ["full-time", "part-time", "contract"], "full-time"))}::public.employment_type, ` +
      `${sqlStr(oneOf(s.status, ["active", "on_leave", "terminated"], "active"))}::public.staff_status, ` +
      `${sqlStr(s.notes)}, ${sqlStr(s.photoUrl)}, ${sqlBool(s.isActive)}, ${sqlTs(s.createdAt)}, ${sqlTs(s.updatedAt)}) ` +
      `on conflict (id) do update set business_id = excluded.business_id, client_id = excluded.client_id, ` +
      `compensation_profile_id = excluded.compensation_profile_id, email = excluded.email, ` +
      `first_name = excluded.first_name, last_name = excluded.last_name, phone = excluded.phone, ` +
      `position = excluded.position, department = excluded.department, date_hired = excluded.date_hired, ` +
      `salary = excluded.salary, salary_type = excluded.salary_type, bill_rate_usd = excluded.bill_rate_usd, ` +
      `employment_type = excluded.employment_type, status = excluded.status, notes = excluded.notes, ` +
      `photo_url = excluded.photo_url, is_active = excluded.is_active;`,
  );

  // Embedded documents keep their original absolute URLs; the data layer
  // passes those through instead of signing them.
  for (const [index, doc] of (s.documents ?? []).entries()) {
    if (!doc?.url) continue;
    lines.push(
      `insert into public.staff_documents (id, staff_id, name, url, type, uploaded_at) values (` +
        `'${uuidV5(`${id}:doc:${index}`)}', '${uuid}', ${sqlStr(doc.name ?? `Document ${index + 1}`)}, ` +
        `${sqlStr(doc.url)}, ${sqlStr(doc.type ?? "application/octet-stream")}, ${sqlTs(doc.uploadedAt)}) ` +
        `on conflict (id) do update set name = excluded.name, url = excluded.url, type = excluded.type;`,
    );
  }
}
lines.push("");
lines.push("commit;");
lines.push("");

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, lines.join("\n"), "utf8");

// ── Report ────────────────────────────────────────────────────────────────

console.log("");
console.log(`Wrote ${outFile}`);
console.log("");
console.log("  businesses            ", businesses.length);
console.log("  admins                ", admins.length);
console.log("  clients               ", clients.length);
console.log("  compensation profiles ", profiles.length);
console.log("  staff                 ", staff.length);

if (stats.skipped.length > 0) {
  console.log("");
  console.log(`  Skipped ${stats.skipped.length} record(s) with missing required fields:`);
  for (const s of stats.skipped.slice(0, 20)) console.log(`    - ${s}`);
  if (stats.skipped.length > 20) console.log(`    ... and ${stats.skipped.length - 20} more`);
}

if (stats.needsPasswordReset.length > 0) {
  console.log("");
  console.log(
    `  ${stats.needsPasswordReset.length} account(s) had no reusable bcrypt hash and will need`,
  );
  console.log("  a password reset. They get an unguessable random password:");
  for (const e of stats.needsPasswordReset.slice(0, 20)) console.log(`    - ${e}`);
  if (stats.needsPasswordReset.length > 20) {
    console.log(`    ... and ${stats.needsPasswordReset.length - 20} more`);
  }
} else if (admins.length + staff.length > 0) {
  console.log("");
  console.log("  All accounts had bcrypt hashes: everyone keeps their current password.");
}

console.log("");
console.log("Collections with no table yet, so not imported:");
console.log("  applicants, attendance, blogs, bookings, comments, eod_reports,");
console.log("  exchange_rates, invoices, jobPosts, leads");
